
from .models import AnalysisResult


class MarkdownFormatter:
    def _format_title(self, result: AnalysisResult) -> str:
        """Format document title"""
        return f"""# Technical Analysis Report\n## {result.issue.issue_id}: {result.issue.title}\n\n---"""

    def _format_effort_estimation(self, result: AnalysisResult) -> str:
        """Format effort estimation section as markdown table"""
        breakdown = result.effort_estimate
        lines = []
        lines.append("## 📊 Effort Estimation\n")
        lines.append("| Task | Hours | Days | Complexity |")
        lines.append("|------|-------|------|------------|")
        for task in breakdown.tasks:
            lines.append(f"| {task.task_name} | {task.estimated_hours:.2f} | {task.estimated_days:.2f} | {task.complexity.value} |")
        lines.append(f"| **TOTAL** | **{breakdown.total_hours:.2f}** | **{breakdown.total_days:.2f}** |  |")
        lines.append(f"| **WITH BUFFER ({breakdown.buffer_percentage}%)** | **{breakdown.total_hours * (1 + breakdown.buffer_percentage/100):.2f}** | **{breakdown.total_with_buffer:.2f}** |  |\n")
        return "\n".join(lines)

    def _format_recommendations(self, result: AnalysisResult) -> str:
        """Format recommendations section"""
        output = ["## 💡 Recommendations\n"]
        for i, rec in enumerate(result.recommendations, 1):
            output.append(f"{i}. {rec}")
        return "\n".join(output)

    def _format_footer(self) -> str:
        """Format footer section"""
        from datetime import datetime
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return f"---\n\n_Generated by Agentic AI System on {timestamp}_"
    """Formats analysis results as Markdown"""
    
    def format(self, result: AnalysisResult) -> str:
        """Generate complete markdown report"""
        
        sections = []
        
        # Title
        sections.append(self._format_title(result))
        
        # Issue Details
        sections.append(self._format_issue_details(result))
        
        # Pseudo Code
        sections.append(self._format_pseudo_code(result))
        
        # Source Code
        sections.append(self._format_source_code(result))
        
        # Effort Estimation
        sections.append(self._format_effort_estimation(result))
        
        # Recommendations
        if result.recommendations:
            sections.append(self._format_recommendations(result))
        
        # Footer
        sections.append(self._format_footer())
        return "\n\n".join(sections)
    
    def _format_issue_details(self, result: AnalysisResult) -> str:
        """Format issue details section"""
        issue = result.issue
        
        return f"""## 📋 Issue Details

| Field | Value |
|-------|-------|
| **Issue ID** | {issue.issue_id} |
| **Type** | {issue.issue_type} |
| **Priority** | {issue.priority} |
| **Status** | {issue.status} |
| **Assignee** | {issue.assignee or 'Unassigned'} |
| **Labels** | {', '.join(issue.labels) if issue.labels else 'None'} |

### Description
{issue.description}"""
    
    def _format_pseudo_code(self, result: AnalysisResult) -> str:
        """Format pseudo code section"""
        pseudo = result.pseudo_code
        
        output = [f"""## 🔍 Pseudo Code

**Complexity Level:** `{pseudo.complexity.value}`
"""]
        
        for section in pseudo.sections:
            output.append(f"""### {section['title']}

```
{section['steps']}
```""")
        
        if pseudo.notes:
            output.append("\n### 📝 Implementation Notes\n")
            for note in pseudo.notes:
                output.append(f"- {note}")
        
        return "\n\n".join(output)
    

    def _format_source_code(self, result: AnalysisResult) -> str:
        """Format source code section"""
        source = result.source_code
        output = [f"## 💻 Source Code ({source.language.upper()})\n"]
        # Dependencies
        if source.dependencies:
            output.append("### 📦 Dependencies\n")
            for dep in source.dependencies:
                output.append(f"- `{dep}`")
            output.append("")
        # Files
        output.append("### 📁 Generated Files\n")
        for i, file_info in enumerate(source.files, 1):
            lang_map = {
                "java": "java",
                "angular": "typescript" if file_info['filename'].endswith('.ts') else "html" if file_info['filename'].endswith('.html') else "scss"
            }
            file_lang = lang_map.get(source.language, source.language)
            output.append(f"#### {i}. {file_info['filename']}")
            if file_info.get('description'):
                output.append(f"*_{file_info['description']}_*")
            output.append(f"```{file_lang}\n{file_info['code']}\n```")
        # Setup Instructions
        if source.setup_instructions:
            output.append("### ⚙️ Setup Instructions\n")
            for i, instruction in enumerate(source.setup_instructions, 1):
                output.append(f"{i}. {instruction}")
        return "\n".join(output)


